version: "3.8"
services:
  reactapp:
    build: ./summer2022-react
    container_name: reactApp_c
    ports:
      - '3000:3000'
    volumes:
      - ./summer2022-react:/app
    stdin_open: true
    tty: true
  ###
  api1:
    build: ./go-restAPI
    container_name: go-Rest
    ports:
      - '8000:8000'
    